apiVersion: apps/v1
kind: Deployment
metadata:
  name: axe-tracing
  labels:
    app: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing
  template:
    metadata:
      labels:
        app: tracing
    spec:
      imagePullSecrets:
        - name: dockerhubkey
      containers:
        - name: axe-tracing
          image: qraftaxe/axe-tracing:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
